services:

  juice-shop:
    build:
      context: ./juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"

  semgrep:
    image: semgrep/semgrep:latest
    container_name: semgrep

    working_dir: /src

    volumes:
      - ./juice-shop:/src
      - ./reports/semgrep:/reports

    command:
      - semgrep
      - scan
      - --config=auto
      - --json
      - --output=/reports/report.json
      - /src
    
  trivy-sbom:
    image: aquasec/trivy:latest
    container_name: trivy-sbom

    working_dir: /project

    volumes:
      - ./juice-shop:/project
      - ./reports/sbom:/reports

    command:
      - fs
      - --format
      - cyclonedx
      - --output
      - /reports/sbom.json
      - /project

  trivy-sca:
    image: aquasec/trivy:latest
    container_name: trivy-sca

    working_dir: /project

    volumes:
      - ./reports/sbom:/sbom
      - ./reports/trivy:/reports

    command:
      - sbom
      - --format
      - json
      - --output
      - /reports/report.json
      - /sbom/sbom.json

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: zap
    working_dir: /zap/wrk
    volumes:
      - ./reports/zap:/zap/wrk

  checkov:
    image: bridgecrew/checkov:latest
    container_name: checkov
    working_dir: /workspace

    volumes:
      - ./:/workspace

    command:
      - --directory
      - /workspace
      - --output
      - json
      - --output-file-path
      - /workspace/reports/checkov/report.json
  
    
  